### ISSUE TITLE
2.0.3 Minimum Stability? 

### ISSUE THREAD

**Issue by mookman288** [ParticleBits/pdo#3]
```
  Problem 1
    - The requested package particlebits/pdo (installed at 2.0.2, required as 2.0.3) is satisfiable by particlebits/pdo[2.0.2] but these conflict with your requirements or minimum-stability.
```

Nothing changed in the `requires` in your lib, so I'm not sure why this error is being thrown. Can you confirm on your end? 

When I set the requirement to `~2.0` in composer.json, the lock file is written as below:

```
             "name": "particlebits/pdo",
              "version": "2.0.2",
```

**Comment by mikegioia** [comment]
@mookman288 Could you try `^2.0` in your composer file and update? Mine is:

```
    "require": {
        "php": ">=7.0",
        "ext-pdo": "*",
...
        "particlebits/pdo": "^2.0",
    },
```

If that works I'll update the docs here. I'm not sure where that error is coming from though.

**Comment by mookman288** [comment]
Are you able to try just putting in "2.0.3" and running composer update from a 2.0.2 install? 

I attempted ^2.0, and it still only locks 2.0.2.

**Comment by mikegioia** [comment]
No definitely don't manually specify the 2.0.3, even if that works it's not right. The newest version shows correctly for me in packagist (fyi) https://packagist.org/packages/particlebits/pdo, but I've encountered your error sometimes with cached copies. Could you try removing the vendor folder first, and if that doesn't work, clearing the composer cache?

Here's a test in a new repo:

```
$ composer init
This command will guide you through creating your composer.json config.

Package name (<vendor>/<name>) [test/pdo-test]:
Description []:
Author [Mike Gioia, n to skip]:
Minimum Stability []:
Package Type (e.g. library, project, metapackage, composer-plugin) []:
License []:

Define your dependencies.

Would you like to define your dev dependencies (require-dev) interactively [yes]?
Search for a package: particlebits/pdo
Enter the version constraint to require (or leave blank to use the latest version):
Using version ^2.0 for particlebits/pdo
Search for a package:

{
    "name": "test/pdo-test",
    "require-dev": {
        "particlebits/pdo": "^2.0"
    },
    "authors": [
        {
            "name": "Mike Gioia"
        }
    ],
    "require": {}
}

Do you confirm generation [yes]? yes
```

Then

```
Test@Pine [03:21 PM] ~/Projects/tests/pdo-test
$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing particlebits/pdo (2.0.3): Downloading (100%)
Writing lock file
Generating autoload files
Test@Pine [03:22 PM] ~/Projects/tests/pdo-test
$
```

Shows it pulls the latest down.

**Comment by mookman288** [comment]
https://getcomposer.org/doc/articles/versions.md#exact-version-constraint

Exact version constraint needs to be supported. It's required for almost all of my projects, because I need to test every update of a third party dependency. 

If it pulls down the most recent for you, it must be on my end, but I did test on three different environments. I'll give it another go with your suggestion above.

**Comment by mikegioia** [comment]
Yea let me clarify, I meant you should be able to get it to work with "^2.0" while we're testing, because if "^2.0" works then "2.0.3" will work. I think this specific error is cache related.

**Comment by mookman288** [comment]
Sorry I didn't mean to sound demanding, I just meant that it's part of Composer. 

Clearing the cache and removing the vendor directory did not work. Here's the snippet I found from running my project from a fresh install (using ^2.0, and 2.0.3) - 

```
Package operations: 22 installs, 0 updates, 0 removals
  - Installing slim/slim (2.6.3): Downloading (100%)
  - Installing particlebits/pdo (2.0.2): Downloading (100%)
```

(I know 2.6.3 is old, but it's stable right now.) 

EDIT1:

When I've got the lock file in there, the error message changes:

```
  Problem 1
    - The requested package particlebits/pdo (locked at 2.0.2, required as 2.0.3) is satisfiable by particlebits/pdo[2.0.2] but these conflict with your requirements or minimum-stability.
```

Although I don't think the information it's providing is any different. 

EDIT2:

Using `require particlebits/pdo` results in:

```
php composer.phar require particlebits/pdo
Using version dev-master for particlebits/pdo
```
```
  - Removing particlebits/pdo (2.0.2)
  - Installing particlebits/pdo (dev-master eb777b8): Cloning eb777b8379
Writing lock file
```

Using `require particlebits/pdo:2.0.3` results in:

```
  - Updating particlebits/pdo (dev-master eb777b8 => 2.0.3):  Checking out 5d3a4e2c57
  - Installing slim/pdo (1.10.0): Downloading (100%)
```

EDIT3:

Possibly related to this commit that doesn't appear to be part of 2.0.3?

https://github.com/ParticleBits/pdo/commit/eb777b837911c68adedcf69a6da85b45ac072420

**Comment by mookman288** [comment]
Hi, 

I just want to update that this might be related to some type of cache, either on github's end or on my end (despite testing in a few different environments.) After a few days, I haven't encountered this issue again.
